<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<groupId>de.egladil.web</groupId>
	<artifactId>filescanner-api</artifactId>
	<version>6.1.0</version>

	<properties>
		<quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
		<quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
		<quarkus.platform.version>3.30.6</quarkus.platform.version>

		<clamav.version>2.1.2</clamav.version>
		<quarkus.tika.version>2.3.0</quarkus.tika.version>

		<mixin-maven-plugin.version>1.0.6</mixin-maven-plugin.version>
		<egladil-maven-mixins.version>1.0.1</egladil-maven-mixins.version>

		<!-- Start mixin-properties -->
		<maven.compiler.release>21</maven.compiler.release>

		<java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
		<maven.compiler.parameters>true</maven.compiler.parameters>
		<!-- Ende mixin-propetries -->
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>${quarkus.platform.group-id}</groupId>
				<artifactId>${quarkus.platform.artifact-id}</artifactId>
				<version>${quarkus.platform.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>

		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
		</dependency>

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
		</dependency>

		<dependency>
			<groupId>xyz.capybara</groupId>
			<artifactId>clamav-client</artifactId>
			<version>${clamav.version}</version>
		</dependency>

		<dependency>
			<groupId>io.quarkiverse.tika</groupId>
			<artifactId>quarkus-tika</artifactId>
			<version>${quarkus.tika.version}</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>

		<dependency>
			<groupId>org.jboss.slf4j</groupId>
			<artifactId>slf4j-jboss-logmanager</artifactId>
		</dependency>

		<!-- Quarkus START -->
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-mailer</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-hibernate-validator</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest-jackson</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-arc</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-smallrye-openapi</artifactId>
		</dependency>


		<!-- START Test scoped dependencies -->
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-junit5</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-test-security</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.testcontainers</groupId>
			<artifactId>junit-jupiter</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-junit5-mockito</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-jacoco</artifactId>
			<scope>test</scope>
		</dependency>
		<!-- END Test scoped dependencies -->
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>${quarkus.platform.group-id}</groupId>
				<artifactId>quarkus-maven-plugin</artifactId>
				<version>${quarkus.platform.version}</version>
				<extensions>true</extensions>
				<executions>
					<execution>
						<goals>
							<goal>build</goal>
							<goal>generate-code</goal>
							<goal>generate-code-tests</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>com.playtika.maven.plugins</groupId>
				<artifactId>mixin-maven-plugin</artifactId>
				<version>${mixin-maven-plugin.version}</version>
				<extensions>true</extensions>
				<configuration>
					<mixins>
						<mixin>
							<groupId>de.egladil</groupId>
							<artifactId>java-core-mixin</artifactId>
							<version>${egladil-maven-mixins.version}</version>
						</mixin>
						<mixin>
							<groupId>de.egladil</groupId>
							<artifactId>java-linting-mixin</artifactId>
							<version>${egladil-maven-mixins.version}</version>
						</mixin>
						<mixin>
							<groupId>de.egladil</groupId>
							<artifactId>java-code-quality-mixin</artifactId>
							<version>${egladil-maven-mixins.version}</version>
						</mixin>
						<mixin>
							<groupId>de.egladil</groupId>
							<artifactId>java-quarkustest-coverage-mixin</artifactId>
							<version>${egladil-maven-mixins.version}</version>
						</mixin>
						<mixin>
							<groupId>de.egladil</groupId>
							<artifactId>java-security-mixin</artifactId>
							<version>${egladil-maven-mixins.version}</version>
						</mixin>
					</mixins>
				</configuration>
			</plugin>

			<plugin>
				<groupId>com.rudikershaw.gitbuildhook</groupId>
				<artifactId>git-build-hook-maven-plugin</artifactId>
				<version>3.6.0</version>
				<configuration>
					<gitConfig>
						<!-- The location of the directory you are using to
						store the Git hooks in your project. -->
						<core.hooksPath>../.git-hooks/</core.hooksPath>
						<!-- Some other project specific git config that you
						want to set. -->
						<custom.configuration>true</custom.configuration>
					</gitConfig>
				</configuration>
				<executions>
					<execution>
						<goals>
							<!-- Sets git config specified under configuration >
							gitConfig. -->
							<goal>configure</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<profiles>
		<profile>
			<id>native</id>
			<activation>
				<property>
					<name>native</name>
				</property>
			</activation>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-failsafe-plugin</artifactId>
						<version>${surefire-plugin.version}</version>
						<executions>
							<execution>
								<goals>
									<goal>integration-test</goal>
									<goal>verify</goal>
								</goals>
								<configuration>
									<systemPropertyVariables>
										<native.image.path>
											${project.build.directory}/${project.build.finalName}-runner</native.image.path>
										<java.util.logging.manager>
											org.jboss.logmanager.LogManager</java.util.logging.manager>
										<maven.home>${maven.home}</maven.home>
									</systemPropertyVariables>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
			<properties>
				<quarkus.package.type>native</quarkus.package.type>
			</properties>
		</profile>
	</profiles>
</project>
